FROM python:3.11.0-buster
ARG DEBIAN_FRONTEND=noninteractive

# パッケージの追加とタイムゾーンの設定
RUN apt-get update && apt-get install -y tzdata \
    && ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# localeの設定
ENV LANG ja_JP.UTF-8
ENV LC_ALL ja_JP.UTF-8
ENV TZ=Asia/Tokyo   

RUN python3 -m pip install --upgrade pip

WORKDIR /notebook
COPY requirements.txt .
RUN pip install -r requirements.txt

# Install nodejs for JupyterLab extension
RUN curl -sL https://deb.nodesource.com/setup_current.x | bash - \
    && apt-get install -y --no-install-recommends nodejs \
    && rm -rf /var/lib/apt/lists/*

RUN jupyter notebook --generate-config -y

# エラーが出たらこいつを削除
RUN jupyter labextension install @lckr/jupyterlab_variableinspector@3.0.7
