version: '3'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: myuser
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    networks:
      - my-network
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:

networks:
  my-network:
    driver: bridge
